name = "DiffusionMap"
uuid = "809424d5-4f20-4f0f-8853-2ca5e8a82a88"
authors = ["Cory Simon <cory.simon@oregonstate.edu>", "Adrian Henle <eahenle@gmail.com>", "Gbenga Fabusola <gbengafabusola@gmail.com>"]
version = "0.1.4"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Aqua = "0.6"
CUDA = "4.0"
StatsBase = "0.33"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
